# -*- coding: utf-8 -*-
"""Tratamento de Dados Chagas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1936ZRdLa3thPB3y7j5XST8IzwwZtzJhL
"""

import pandas as pd
from ClasseMultiTeste import MultiTeste

dataset = pd.read_excel("Banco de Dados Geral rep-Chagas Modificado.xlsx")
dataset = dataset.drop(columns=["NYHA","Rassi escore","Classificação"])


## MAIN - Execução

coluna = "Nome do Paciente"
MT = MultiTeste(dataset, coluna, 80, "exames")
resposta = MT.RegressaoMedica()
print(resposta)

ordenada = MT.OrdenaMetrica(resposta, 'MSE', "sim")
print(ordenada)

